if(EXISTS "/home/vika/Learning/Coursera_C++_MFTI/Yellow_Belt/submodulesFinalCaseTESTS/EventParserFinalCase/__build/EventParserFinalCase_tests[1]_tests.cmake")
  include("/home/vika/Learning/Coursera_C++_MFTI/Yellow_Belt/submodulesFinalCaseTESTS/EventParserFinalCase/__build/EventParserFinalCase_tests[1]_tests.cmake")
else()
  add_test(EventParserFinalCase_tests_NOT_BUILT EventParserFinalCase_tests_NOT_BUILT)
endif()
