add_test( Parser.OneNumber_OneOperation [==[/home/vika/Learning/Coursera_C++_MFTI/Yellow_Belt/BuildingEquation/__build/BuildingEquation_tests]==] [==[--gtest_filter=Parser.OneNumber_OneOperation]==] --gtest_also_run_disabled_tests)
set_tests_properties( Parser.OneNumber_OneOperation PROPERTIES WORKING_DIRECTORY [==[/home/vika/Learning/Coursera_C++_MFTI/Yellow_Belt/BuildingEquation/__build]==])
add_test( Parser.OneNumber_OneOperation2 [==[/home/vika/Learning/Coursera_C++_MFTI/Yellow_Belt/BuildingEquation/__build/BuildingEquation_tests]==] [==[--gtest_filter=Parser.OneNumber_OneOperation2]==] --gtest_also_run_disabled_tests)
set_tests_properties( Parser.OneNumber_OneOperation2 PROPERTIES WORKING_DIRECTORY [==[/home/vika/Learning/Coursera_C++_MFTI/Yellow_Belt/BuildingEquation/__build]==])
add_test( Parser.OneNumber_ThreeOperations [==[/home/vika/Learning/Coursera_C++_MFTI/Yellow_Belt/BuildingEquation/__build/BuildingEquation_tests]==] [==[--gtest_filter=Parser.OneNumber_ThreeOperations]==] --gtest_also_run_disabled_tests)
set_tests_properties( Parser.OneNumber_ThreeOperations PROPERTIES WORKING_DIRECTORY [==[/home/vika/Learning/Coursera_C++_MFTI/Yellow_Belt/BuildingEquation/__build]==])
add_test( Parser.OneNumber_ThreeOperations2 [==[/home/vika/Learning/Coursera_C++_MFTI/Yellow_Belt/BuildingEquation/__build/BuildingEquation_tests]==] [==[--gtest_filter=Parser.OneNumber_ThreeOperations2]==] --gtest_also_run_disabled_tests)
set_tests_properties( Parser.OneNumber_ThreeOperations2 PROPERTIES WORKING_DIRECTORY [==[/home/vika/Learning/Coursera_C++_MFTI/Yellow_Belt/BuildingEquation/__build]==])
set( BuildingEquation_tests_TESTS Parser.OneNumber_OneOperation Parser.OneNumber_OneOperation2 Parser.OneNumber_ThreeOperations Parser.OneNumber_ThreeOperations2)
