add_test( PrintTest.Correct_Output [==[/home/vika/Learning/Coursera_C++_MFTI/Red_Belt/print_values/__build/print_values_tests]==] [==[--gtest_filter=PrintTest.Correct_Output]==] --gtest_also_run_disabled_tests)
set_tests_properties( PrintTest.Correct_Output PROPERTIES WORKING_DIRECTORY [==[/home/vika/Learning/Coursera_C++_MFTI/Red_Belt/print_values/__build]==])
add_test( PrintTest.Correct_Output1 [==[/home/vika/Learning/Coursera_C++_MFTI/Red_Belt/print_values/__build/print_values_tests]==] [==[--gtest_filter=PrintTest.Correct_Output1]==] --gtest_also_run_disabled_tests)
set_tests_properties( PrintTest.Correct_Output1 PROPERTIES WORKING_DIRECTORY [==[/home/vika/Learning/Coursera_C++_MFTI/Red_Belt/print_values/__build]==])
add_test( PrintTest.Correct_Output2 [==[/home/vika/Learning/Coursera_C++_MFTI/Red_Belt/print_values/__build/print_values_tests]==] [==[--gtest_filter=PrintTest.Correct_Output2]==] --gtest_also_run_disabled_tests)
set_tests_properties( PrintTest.Correct_Output2 PROPERTIES WORKING_DIRECTORY [==[/home/vika/Learning/Coursera_C++_MFTI/Red_Belt/print_values/__build]==])
add_test( PrintTest.Correct_Output3 [==[/home/vika/Learning/Coursera_C++_MFTI/Red_Belt/print_values/__build/print_values_tests]==] [==[--gtest_filter=PrintTest.Correct_Output3]==] --gtest_also_run_disabled_tests)
set_tests_properties( PrintTest.Correct_Output3 PROPERTIES WORKING_DIRECTORY [==[/home/vika/Learning/Coursera_C++_MFTI/Red_Belt/print_values/__build]==])
set( print_values_tests_TESTS PrintTest.Correct_Output PrintTest.Correct_Output1 PrintTest.Correct_Output2 PrintTest.Correct_Output3)
