add_test( ParseCondition.DateComparisonNode [==[/home/vika/Learning/Coursera_C++_MFTI/Yellow_Belt/submodules/del/__build/del_tests]==] [==[--gtest_filter=ParseCondition.DateComparisonNode]==] --gtest_also_run_disabled_tests)
set_tests_properties( ParseCondition.DateComparisonNode PROPERTIES WORKING_DIRECTORY [==[/home/vika/Learning/Coursera_C++_MFTI/Yellow_Belt/submodules/del/__build]==])
add_test( ParseCondition.EventComparisonNode [==[/home/vika/Learning/Coursera_C++_MFTI/Yellow_Belt/submodules/del/__build/del_tests]==] [==[--gtest_filter=ParseCondition.EventComparisonNode]==] --gtest_also_run_disabled_tests)
set_tests_properties( ParseCondition.EventComparisonNode PROPERTIES WORKING_DIRECTORY [==[/home/vika/Learning/Coursera_C++_MFTI/Yellow_Belt/submodules/del/__build]==])
add_test( ParseCondition.LogicalOperationNode [==[/home/vika/Learning/Coursera_C++_MFTI/Yellow_Belt/submodules/del/__build/del_tests]==] [==[--gtest_filter=ParseCondition.LogicalOperationNode]==] --gtest_also_run_disabled_tests)
set_tests_properties( ParseCondition.LogicalOperationNode PROPERTIES WORKING_DIRECTORY [==[/home/vika/Learning/Coursera_C++_MFTI/Yellow_Belt/submodules/del/__build]==])
add_test( ParseCondition.LogicalOperationNode2 [==[/home/vika/Learning/Coursera_C++_MFTI/Yellow_Belt/submodules/del/__build/del_tests]==] [==[--gtest_filter=ParseCondition.LogicalOperationNode2]==] --gtest_also_run_disabled_tests)
set_tests_properties( ParseCondition.LogicalOperationNode2 PROPERTIES WORKING_DIRECTORY [==[/home/vika/Learning/Coursera_C++_MFTI/Yellow_Belt/submodules/del/__build]==])
set( del_tests_TESTS ParseCondition.DateComparisonNode ParseCondition.EventComparisonNode ParseCondition.LogicalOperationNode ParseCondition.LogicalOperationNode2)
